// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: appbus.proto
// Protobuf Java Version: 4.31.0

package com.juggle.chat.services;

@com.google.protobuf.Generated
public final class Appbus {
  private Appbus() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      Appbus.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.juggle.chat.services.ApiKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appkey = 1;</code>
     * @return The appkey.
     */
    java.lang.String getAppkey();
    /**
     * <code>string appkey = 1;</code>
     * @return The bytes for appkey.
     */
    com.google.protobuf.ByteString
        getAppkeyBytes();

    /**
     * <code>int64 created_time = 2;</code>
     * @return The createdTime.
     */
    long getCreatedTime();
  }
  /**
   * Protobuf type {@code com.juggle.chat.services.ApiKey}
   */
  public static final class ApiKey extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.juggle.chat.services.ApiKey)
      ApiKeyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        ApiKey.class.getName());
    }
    // Use ApiKey.newBuilder() to construct.
    private ApiKey(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ApiKey() {
      appkey_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_ApiKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_ApiKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.juggle.chat.services.Appbus.ApiKey.class, com.juggle.chat.services.Appbus.ApiKey.Builder.class);
    }

    public static final int APPKEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object appkey_ = "";
    /**
     * <code>string appkey = 1;</code>
     * @return The appkey.
     */
    @java.lang.Override
    public java.lang.String getAppkey() {
      java.lang.Object ref = appkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appkey_ = s;
        return s;
      }
    }
    /**
     * <code>string appkey = 1;</code>
     * @return The bytes for appkey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      java.lang.Object ref = appkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_TIME_FIELD_NUMBER = 2;
    private long createdTime_ = 0L;
    /**
     * <code>int64 created_time = 2;</code>
     * @return The createdTime.
     */
    @java.lang.Override
    public long getCreatedTime() {
      return createdTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appkey_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, appkey_);
      }
      if (createdTime_ != 0L) {
        output.writeInt64(2, createdTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appkey_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, appkey_);
      }
      if (createdTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createdTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.juggle.chat.services.Appbus.ApiKey)) {
        return super.equals(obj);
      }
      com.juggle.chat.services.Appbus.ApiKey other = (com.juggle.chat.services.Appbus.ApiKey) obj;

      if (!getAppkey()
          .equals(other.getAppkey())) return false;
      if (getCreatedTime()
          != other.getCreatedTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppkey().hashCode();
      hash = (37 * hash) + CREATED_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.juggle.chat.services.Appbus.ApiKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.juggle.chat.services.Appbus.ApiKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.juggle.chat.services.Appbus.ApiKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.juggle.chat.services.Appbus.ApiKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.juggle.chat.services.ApiKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.juggle.chat.services.ApiKey)
        com.juggle.chat.services.Appbus.ApiKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_ApiKey_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_ApiKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.juggle.chat.services.Appbus.ApiKey.class, com.juggle.chat.services.Appbus.ApiKey.Builder.class);
      }

      // Construct using com.juggle.chat.services.Appbus.ApiKey.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        appkey_ = "";
        createdTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_ApiKey_descriptor;
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.ApiKey getDefaultInstanceForType() {
        return com.juggle.chat.services.Appbus.ApiKey.getDefaultInstance();
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.ApiKey build() {
        com.juggle.chat.services.Appbus.ApiKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.ApiKey buildPartial() {
        com.juggle.chat.services.Appbus.ApiKey result = new com.juggle.chat.services.Appbus.ApiKey(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.juggle.chat.services.Appbus.ApiKey result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.appkey_ = appkey_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.createdTime_ = createdTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.juggle.chat.services.Appbus.ApiKey) {
          return mergeFrom((com.juggle.chat.services.Appbus.ApiKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.juggle.chat.services.Appbus.ApiKey other) {
        if (other == com.juggle.chat.services.Appbus.ApiKey.getDefaultInstance()) return this;
        if (!other.getAppkey().isEmpty()) {
          appkey_ = other.appkey_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getCreatedTime() != 0L) {
          setCreatedTime(other.getCreatedTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                appkey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                createdTime_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object appkey_ = "";
      /**
       * <code>string appkey = 1;</code>
       * @return The appkey.
       */
      public java.lang.String getAppkey() {
        java.lang.Object ref = appkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appkey = 1;</code>
       * @return The bytes for appkey.
       */
      public com.google.protobuf.ByteString
          getAppkeyBytes() {
        java.lang.Object ref = appkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appkey = 1;</code>
       * @param value The appkey to set.
       * @return This builder for chaining.
       */
      public Builder setAppkey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        appkey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string appkey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppkey() {
        appkey_ = getDefaultInstance().getAppkey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string appkey = 1;</code>
       * @param value The bytes for appkey to set.
       * @return This builder for chaining.
       */
      public Builder setAppkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        appkey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long createdTime_ ;
      /**
       * <code>int64 created_time = 2;</code>
       * @return The createdTime.
       */
      @java.lang.Override
      public long getCreatedTime() {
        return createdTime_;
      }
      /**
       * <code>int64 created_time = 2;</code>
       * @param value The createdTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedTime(long value) {

        createdTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 created_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreatedTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createdTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.juggle.chat.services.ApiKey)
    }

    // @@protoc_insertion_point(class_scope:com.juggle.chat.services.ApiKey)
    private static final com.juggle.chat.services.Appbus.ApiKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.juggle.chat.services.Appbus.ApiKey();
    }

    public static com.juggle.chat.services.Appbus.ApiKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiKey>
        PARSER = new com.google.protobuf.AbstractParser<ApiKey>() {
      @java.lang.Override
      public ApiKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApiKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiKey> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.juggle.chat.services.Appbus.ApiKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.juggle.chat.services.AuthToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appkey = 1;</code>
     * @return The appkey.
     */
    java.lang.String getAppkey();
    /**
     * <code>string appkey = 1;</code>
     * @return The bytes for appkey.
     */
    com.google.protobuf.ByteString
        getAppkeyBytes();

    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>bytes tokenValue = 3;</code>
     * @return The tokenValue.
     */
    com.google.protobuf.ByteString getTokenValue();
  }
  /**
   * Protobuf type {@code com.juggle.chat.services.AuthToken}
   */
  public static final class AuthToken extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.juggle.chat.services.AuthToken)
      AuthTokenOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        AuthToken.class.getName());
    }
    // Use AuthToken.newBuilder() to construct.
    private AuthToken(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AuthToken() {
      appkey_ = "";
      tokenValue_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.juggle.chat.services.Appbus.AuthToken.class, com.juggle.chat.services.Appbus.AuthToken.Builder.class);
    }

    public static final int APPKEY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object appkey_ = "";
    /**
     * <code>string appkey = 1;</code>
     * @return The appkey.
     */
    @java.lang.Override
    public java.lang.String getAppkey() {
      java.lang.Object ref = appkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appkey_ = s;
        return s;
      }
    }
    /**
     * <code>string appkey = 1;</code>
     * @return The bytes for appkey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      java.lang.Object ref = appkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_ = 0;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int TOKENVALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString tokenValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes tokenValue = 3;</code>
     * @return The tokenValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTokenValue() {
      return tokenValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appkey_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, appkey_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (!tokenValue_.isEmpty()) {
        output.writeBytes(3, tokenValue_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(appkey_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, appkey_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (!tokenValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, tokenValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.juggle.chat.services.Appbus.AuthToken)) {
        return super.equals(obj);
      }
      com.juggle.chat.services.Appbus.AuthToken other = (com.juggle.chat.services.Appbus.AuthToken) obj;

      if (!getAppkey()
          .equals(other.getAppkey())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getTokenValue()
          .equals(other.getTokenValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppkey().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + TOKENVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getTokenValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.juggle.chat.services.Appbus.AuthToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.juggle.chat.services.Appbus.AuthToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.juggle.chat.services.Appbus.AuthToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.juggle.chat.services.Appbus.AuthToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.juggle.chat.services.AuthToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.juggle.chat.services.AuthToken)
        com.juggle.chat.services.Appbus.AuthTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthToken_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.juggle.chat.services.Appbus.AuthToken.class, com.juggle.chat.services.Appbus.AuthToken.Builder.class);
      }

      // Construct using com.juggle.chat.services.Appbus.AuthToken.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        appkey_ = "";
        version_ = 0;
        tokenValue_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthToken_descriptor;
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.AuthToken getDefaultInstanceForType() {
        return com.juggle.chat.services.Appbus.AuthToken.getDefaultInstance();
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.AuthToken build() {
        com.juggle.chat.services.Appbus.AuthToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.AuthToken buildPartial() {
        com.juggle.chat.services.Appbus.AuthToken result = new com.juggle.chat.services.Appbus.AuthToken(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.juggle.chat.services.Appbus.AuthToken result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.appkey_ = appkey_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.tokenValue_ = tokenValue_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.juggle.chat.services.Appbus.AuthToken) {
          return mergeFrom((com.juggle.chat.services.Appbus.AuthToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.juggle.chat.services.Appbus.AuthToken other) {
        if (other == com.juggle.chat.services.Appbus.AuthToken.getDefaultInstance()) return this;
        if (!other.getAppkey().isEmpty()) {
          appkey_ = other.appkey_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getTokenValue().isEmpty()) {
          setTokenValue(other.getTokenValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                appkey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                tokenValue_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object appkey_ = "";
      /**
       * <code>string appkey = 1;</code>
       * @return The appkey.
       */
      public java.lang.String getAppkey() {
        java.lang.Object ref = appkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appkey = 1;</code>
       * @return The bytes for appkey.
       */
      public com.google.protobuf.ByteString
          getAppkeyBytes() {
        java.lang.Object ref = appkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appkey = 1;</code>
       * @param value The appkey to set.
       * @return This builder for chaining.
       */
      public Builder setAppkey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        appkey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string appkey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppkey() {
        appkey_ = getDefaultInstance().getAppkey();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string appkey = 1;</code>
       * @param value The bytes for appkey to set.
       * @return This builder for chaining.
       */
      public Builder setAppkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        appkey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {

        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString tokenValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes tokenValue = 3;</code>
       * @return The tokenValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTokenValue() {
        return tokenValue_;
      }
      /**
       * <code>bytes tokenValue = 3;</code>
       * @param value The tokenValue to set.
       * @return This builder for chaining.
       */
      public Builder setTokenValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        tokenValue_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes tokenValue = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTokenValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tokenValue_ = getDefaultInstance().getTokenValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.juggle.chat.services.AuthToken)
    }

    // @@protoc_insertion_point(class_scope:com.juggle.chat.services.AuthToken)
    private static final com.juggle.chat.services.Appbus.AuthToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.juggle.chat.services.Appbus.AuthToken();
    }

    public static com.juggle.chat.services.Appbus.AuthToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthToken>
        PARSER = new com.google.protobuf.AbstractParser<AuthToken>() {
      @java.lang.Override
      public AuthToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AuthToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthToken> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.juggle.chat.services.Appbus.AuthToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthTokenValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.juggle.chat.services.AuthTokenValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string deviceId = 2;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <code>string deviceId = 2;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>int64 tokenTime = 3;</code>
     * @return The tokenTime.
     */
    long getTokenTime();
  }
  /**
   * Protobuf type {@code com.juggle.chat.services.AuthTokenValue}
   */
  public static final class AuthTokenValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.juggle.chat.services.AuthTokenValue)
      AuthTokenValueOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        AuthTokenValue.class.getName());
    }
    // Use AuthTokenValue.newBuilder() to construct.
    private AuthTokenValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AuthTokenValue() {
      userId_ = "";
      deviceId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthTokenValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthTokenValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.juggle.chat.services.Appbus.AuthTokenValue.class, com.juggle.chat.services.Appbus.AuthTokenValue.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object deviceId_ = "";
    /**
     * <code>string deviceId = 2;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 2;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKENTIME_FIELD_NUMBER = 3;
    private long tokenTime_ = 0L;
    /**
     * <code>int64 tokenTime = 3;</code>
     * @return The tokenTime.
     */
    @java.lang.Override
    public long getTokenTime() {
      return tokenTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, deviceId_);
      }
      if (tokenTime_ != 0L) {
        output.writeInt64(3, tokenTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deviceId_);
      }
      if (tokenTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, tokenTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.juggle.chat.services.Appbus.AuthTokenValue)) {
        return super.equals(obj);
      }
      com.juggle.chat.services.Appbus.AuthTokenValue other = (com.juggle.chat.services.Appbus.AuthTokenValue) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (getTokenTime()
          != other.getTokenTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + TOKENTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTokenTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.juggle.chat.services.Appbus.AuthTokenValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.juggle.chat.services.Appbus.AuthTokenValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.juggle.chat.services.Appbus.AuthTokenValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.juggle.chat.services.Appbus.AuthTokenValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.juggle.chat.services.AuthTokenValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.juggle.chat.services.AuthTokenValue)
        com.juggle.chat.services.Appbus.AuthTokenValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthTokenValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthTokenValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.juggle.chat.services.Appbus.AuthTokenValue.class, com.juggle.chat.services.Appbus.AuthTokenValue.Builder.class);
      }

      // Construct using com.juggle.chat.services.Appbus.AuthTokenValue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = "";
        deviceId_ = "";
        tokenTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.juggle.chat.services.Appbus.internal_static_com_juggle_chat_services_AuthTokenValue_descriptor;
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.AuthTokenValue getDefaultInstanceForType() {
        return com.juggle.chat.services.Appbus.AuthTokenValue.getDefaultInstance();
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.AuthTokenValue build() {
        com.juggle.chat.services.Appbus.AuthTokenValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.juggle.chat.services.Appbus.AuthTokenValue buildPartial() {
        com.juggle.chat.services.Appbus.AuthTokenValue result = new com.juggle.chat.services.Appbus.AuthTokenValue(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.juggle.chat.services.Appbus.AuthTokenValue result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.deviceId_ = deviceId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.tokenTime_ = tokenTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.juggle.chat.services.Appbus.AuthTokenValue) {
          return mergeFrom((com.juggle.chat.services.Appbus.AuthTokenValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.juggle.chat.services.Appbus.AuthTokenValue other) {
        if (other == com.juggle.chat.services.Appbus.AuthTokenValue.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getTokenTime() != 0L) {
          setTokenTime(other.getTokenTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                deviceId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                tokenTime_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string deviceId = 2;</code>
       * @return The deviceId.
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceId = 2;</code>
       * @return The bytes for deviceId.
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 2;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        deviceId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        deviceId_ = getDefaultInstance().getDeviceId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 2;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        deviceId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long tokenTime_ ;
      /**
       * <code>int64 tokenTime = 3;</code>
       * @return The tokenTime.
       */
      @java.lang.Override
      public long getTokenTime() {
        return tokenTime_;
      }
      /**
       * <code>int64 tokenTime = 3;</code>
       * @param value The tokenTime to set.
       * @return This builder for chaining.
       */
      public Builder setTokenTime(long value) {

        tokenTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 tokenTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTokenTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tokenTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.juggle.chat.services.AuthTokenValue)
    }

    // @@protoc_insertion_point(class_scope:com.juggle.chat.services.AuthTokenValue)
    private static final com.juggle.chat.services.Appbus.AuthTokenValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.juggle.chat.services.Appbus.AuthTokenValue();
    }

    public static com.juggle.chat.services.Appbus.AuthTokenValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthTokenValue>
        PARSER = new com.google.protobuf.AbstractParser<AuthTokenValue>() {
      @java.lang.Override
      public AuthTokenValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AuthTokenValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthTokenValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.juggle.chat.services.Appbus.AuthTokenValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_juggle_chat_services_ApiKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_juggle_chat_services_ApiKey_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_juggle_chat_services_AuthToken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_juggle_chat_services_AuthToken_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_juggle_chat_services_AuthTokenValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_juggle_chat_services_AuthTokenValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014appbus.proto\022\030com.juggle.chat.services" +
      "\".\n\006ApiKey\022\016\n\006appkey\030\001 \001(\t\022\024\n\014created_ti" +
      "me\030\002 \001(\003\"@\n\tAuthToken\022\016\n\006appkey\030\001 \001(\t\022\017\n" +
      "\007version\030\002 \001(\005\022\022\n\ntokenValue\030\003 \001(\014\"E\n\016Au" +
      "thTokenValue\022\016\n\006userId\030\001 \001(\t\022\020\n\010deviceId" +
      "\030\002 \001(\t\022\021\n\ttokenTime\030\003 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_juggle_chat_services_ApiKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_juggle_chat_services_ApiKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_juggle_chat_services_ApiKey_descriptor,
        new java.lang.String[] { "Appkey", "CreatedTime", });
    internal_static_com_juggle_chat_services_AuthToken_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_juggle_chat_services_AuthToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_juggle_chat_services_AuthToken_descriptor,
        new java.lang.String[] { "Appkey", "Version", "TokenValue", });
    internal_static_com_juggle_chat_services_AuthTokenValue_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_juggle_chat_services_AuthTokenValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_juggle_chat_services_AuthTokenValue_descriptor,
        new java.lang.String[] { "UserId", "DeviceId", "TokenTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
